#ifndef MACHINETALK_GLOBAL_H
#define MACHINETALK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MACHINETALK_LIBRARY)
#  define MACHINETALKSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MACHINETALKSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MACHINETALK_GLOBAL_H
