/****************************************************************************
**
** This file was generated by a code generator based on imatix/gsl
** Any changes in this file will be lost.
**
****************************************************************************/
#ifndef PARAM_PARAM_SERVER_H
#define PARAM_PARAM_SERVER_H
#include <QObject>
#include <QSet>
#include <QQmlParserStatus>
#include <nzmqt/nzmqt.hpp>
#include <machinetalk/protobuf/message.pb.h>
#include "../common/rpcservice.h"
#include "../common/publish.h"

namespace machinetalk { namespace param {

class ParamServer
    : public QObject
    , public QQmlParserStatus
{
    Q_OBJECT
    Q_INTERFACES(QQmlParserStatus)
    Q_PROPERTY(bool ready READ ready WRITE setReady NOTIFY readyChanged)
    Q_PROPERTY(QString paramcmdUri READ paramcmdUri WRITE setParamcmdUri NOTIFY paramcmdUriChanged)
    Q_PROPERTY(QString paramUri READ paramUri WRITE setParamUri NOTIFY paramUriChanged)
    Q_PROPERTY(QString debugName READ debugName WRITE setDebugName NOTIFY debugNameChanged)
    Q_PROPERTY(State connectionState READ state NOTIFY stateChanged)
    Q_PROPERTY(QString errorString READ errorString NOTIFY errorStringChanged)
    Q_PROPERTY(int paramHeartbeatInterval READ paramHeartbeatInterval WRITE setParamHeartbeatInterval NOTIFY paramHeartbeatIntervalChanged)
    Q_ENUMS(State)

public:
    explicit ParamServer(QObject *parent = nullptr);
    ~ParamServer();

    enum class State {
        Down = 0,
        Up = 1,
    };

    void classBegin() {}
    /** componentComplete is executed when the QML component is fully loaded */
    void componentComplete()
    {
        m_componentCompleted = true;

        if (m_ready == true)    // the component was set to ready before it was completed
        {
            start();
        }
    }

    QString paramcmdUri() const
    {
        return m_paramcmdChannel->socketUri();
    }

    QString paramUri() const
    {
        return m_paramChannel->socketUri();
    }

    QString debugName() const
    {
        return m_debugName;
    }

    State state() const
    {
        return m_state;
    }

    QString errorString() const
    {
        return m_errorString;
    }

    int paramHeartbeatInterval() const
    {
        return m_paramChannel->heartbeatInterval();
    }

    bool ready() const
    {
        return m_ready;
    }

public slots:

    void setParamcmdUri(const QString &uri)
    {
        m_paramcmdChannel->setSocketUri(uri);
    }

    void setParamUri(const QString &uri)
    {
        m_paramChannel->setSocketUri(uri);
    }

    void setDebugName(const QString &debugName)
    {
        if (m_debugName == debugName) {
            return;
        }

        m_debugName = debugName;
        emit debugNameChanged(debugName);
    }

    void setParamHeartbeatInterval(int interval)
    {
        m_paramChannel->setHeartbeatInterval(interval);
    }

    void setReady(bool ready)
    {
        if (m_ready == ready) {
            return;
        }

        m_ready = ready;
        emit readyChanged(ready);

        if (m_componentCompleted == false)
        {
            return;
        }

        if (m_ready)
        {
            start();
        }
        else
        {
            stop();
        }
    }


    void sendParamMessage(const QByteArray &topic, ContainerType type, Container &tx);
    void sendFullUpdate(const QByteArray &topic, Container &tx);
    void sendIncrementalUpdate(const QByteArray &topic, Container &tx);

protected:

private:
    bool m_componentCompleted;
    bool m_ready;
    QString m_debugName;

    common::RpcService *m_paramcmdChannel;
    common::Publish *m_paramChannel;

    State         m_state;
    State         m_previousState;
    QString       m_errorString;
    // more efficient to reuse a protobuf Messages
    Container m_paramcmdRx;
    Container m_paramTx;

private slots:

    void startParamcmdChannel();
    void stopParamcmdChannel();
    void processParamcmdChannelMessage(const QByteArray &topic, const Container &rx);

    void startParamChannel();
    void stopParamChannel();

    void fsmDown();
    void fsmDownConnectEvent();
    void fsmUp();
    void fsmUpDisconnectEvent();

    virtual void incrementalUpdateReceived(const QByteArray &topic, const Container &rx) = 0;

signals:
    void paramcmdUriChanged(const QString &uri);
    void paramUriChanged(const QString &uri);
    void paramcmdMessageReceived(const QByteArray &topic, const Container &rx);
    void debugNameChanged(const QString &debugName);
    void stateChanged(ParamServer::State state);
    void errorStringChanged(const QString &errorString);
    void paramHeartbeatIntervalChanged(int interval);
    void readyChanged(bool ready);
    // fsm
    void fsmDownEntered(QPrivateSignal);
    void fsmDownExited(QPrivateSignal);
    void fsmDownConnect(QPrivateSignal);
    void fsmUpEntered(QPrivateSignal);
    void fsmUpExited(QPrivateSignal);
    void fsmUpDisconnect(QPrivateSignal);
};

} } // namespace machinetalk::param
#endif // PARAM_PARAM_SERVER_H
