/****************************************************************************
**
** This file was generated by a code generator based on imatix/gsl
** Any changes in this file will be lost.
**
****************************************************************************/
#ifndef APPLICATION_COMMAND_BASE_H
#define APPLICATION_COMMAND_BASE_H
#include <QObject>
#include <QSet>
#include <QQmlParserStatus>
#include <nzmqt/nzmqt.hpp>
#include <machinetalk/protobuf/message.pb.h>
#include "../common/rpcclient.h"

namespace machinetalk { namespace application {

class CommandBase
    : public QObject
    , public QQmlParserStatus
{
    Q_OBJECT
    Q_INTERFACES(QQmlParserStatus)
    Q_PROPERTY(bool ready READ ready WRITE setReady NOTIFY readyChanged)
    Q_PROPERTY(QString commandUri READ commandUri WRITE setCommandUri NOTIFY commandUriChanged)
    Q_PROPERTY(QString debugName READ debugName WRITE setDebugName NOTIFY debugNameChanged)
    Q_PROPERTY(State connectionState READ state NOTIFY stateChanged)
    Q_PROPERTY(QString errorString READ errorString NOTIFY errorStringChanged)
    Q_PROPERTY(int commandHeartbeatInterval READ commandHeartbeatInterval WRITE setCommandHeartbeatInterval NOTIFY commandHeartbeatIntervalChanged)
    Q_ENUMS(State)

public:
    explicit CommandBase(QObject *parent = nullptr);
    ~CommandBase();

    enum class State {
        Down = 0,
        Trying = 1,
        Up = 2,
    };

    void classBegin() {}
    /** componentComplete is executed when the QML component is fully loaded */
    void componentComplete()
    {
        m_componentCompleted = true;

        if (m_ready == true)    // the component was set to ready before it was completed
        {
            start();
        }
    }

    QString commandUri() const
    {
        return m_commandChannel->socketUri();
    }

    QString debugName() const
    {
        return m_debugName;
    }

    State state() const
    {
        return m_state;
    }

    QString errorString() const
    {
        return m_errorString;
    }

    int commandHeartbeatInterval() const
    {
        return m_commandChannel->heartbeatInterval();
    }

    bool ready() const
    {
        return m_ready;
    }

public slots:

    void setCommandUri(const QString &uri)
    {
        m_commandChannel->setSocketUri(uri);
    }

    void setDebugName(const QString &debugName)
    {
        if (m_debugName == debugName) {
            return;
        }

        m_debugName = debugName;
        emit debugNameChanged(debugName);
    }

    void setCommandHeartbeatInterval(int interval)
    {
        m_commandChannel->setHeartbeatInterval(interval);
    }

    void setReady(bool ready)
    {
        if (m_ready == ready) {
            return;
        }

        m_ready = ready;
        emit readyChanged(ready);

        if (m_componentCompleted == false)
        {
            return;
        }

        if (m_ready)
        {
            start();
        }
        else
        {
            stop();
        }
    }


    void sendCommandMessage(ContainerType type, Container &tx);
    void sendEmcTaskAbort(Container &tx);
    void sendEmcTaskPlanRun(Container &tx);
    void sendEmcTaskPlanPause(Container &tx);
    void sendEmcTaskPlanStep(Container &tx);
    void sendEmcTaskPlanResume(Container &tx);
    void sendEmcSetDebug(Container &tx);
    void sendEmcCoolantFloodOn(Container &tx);
    void sendEmcCoolantFloodOff(Container &tx);
    void sendEmcAxisHome(Container &tx);
    void sendEmcAxisJog(Container &tx);
    void sendEmcAxisAbort(Container &tx);
    void sendEmcAxisIncrJog(Container &tx);
    void sendEmcToolLoadToolTable(Container &tx);
    void sendEmcToolUpdateToolTable(Container &tx);
    void sendEmcTaskPlanExecute(Container &tx);
    void sendEmcCoolantMistOn(Container &tx);
    void sendEmcCoolantMistOff(Container &tx);
    void sendEmcTaskPlanInit(Container &tx);
    void sendEmcTaskPlanOpen(Container &tx);
    void sendEmcTaskPlanSetOptionalStop(Container &tx);
    void sendEmcTaskPlanSetBlockDelete(Container &tx);
    void sendEmcTaskSetMode(Container &tx);
    void sendEmcTaskSetState(Container &tx);
    void sendEmcTrajSetSoEnable(Container &tx);
    void sendEmcTrajSetFhEnable(Container &tx);
    void sendEmcTrajSetFoEnable(Container &tx);
    void sendEmcTrajSetMaxVelocity(Container &tx);
    void sendEmcTrajSetMode(Container &tx);
    void sendEmcTrajSetScale(Container &tx);
    void sendEmcTrajSetRapidScale(Container &tx);
    void sendEmcTrajSetSpindleScale(Container &tx);
    void sendEmcTrajSetTeleopEnable(Container &tx);
    void sendEmcTrajSetTeleopVector(Container &tx);
    void sendEmcToolSetOffset(Container &tx);
    void sendEmcAxisOverrideLimits(Container &tx);
    void sendEmcSpindleConstant(Container &tx);
    void sendEmcSpindleDecrease(Container &tx);
    void sendEmcSpindleIncrease(Container &tx);
    void sendEmcSpindleOff(Container &tx);
    void sendEmcSpindleOn(Container &tx);
    void sendEmcSpindleBrakeEngage(Container &tx);
    void sendEmcSpindleBrakeRelease(Container &tx);
    void sendEmcMotionSetAout(Container &tx);
    void sendEmcMotionSetDout(Container &tx);
    void sendEmcMotionAdaptive(Container &tx);
    void sendEmcAxisSetMaxPositionLimit(Container &tx);
    void sendEmcAxisSetMinPositionLimit(Container &tx);
    void sendEmcAxisUnhome(Container &tx);
    void sendShutdown(Container &tx);

protected:
    void start(); // start trigger
    void stop(); // stop trigger

private:
    bool m_componentCompleted;
    bool m_ready;
    QString m_debugName;

    common::RpcClient *m_commandChannel;

    State         m_state;
    State         m_previousState;
    QString       m_errorString;
    // more efficient to reuse a protobuf Messages
    Container m_commandRx;
    Container m_commandTx;

private slots:

    void startCommandChannel();
    void stopCommandChannel();
    void commandChannelStateChanged(common::RpcClient::State state);
    void processCommandChannelMessage(const Container &rx);

    void fsmDown();
    void fsmDownConnectEvent();
    void fsmTrying();
    void fsmTryingCommandUpEvent();
    void fsmTryingDisconnectEvent();
    void fsmUp();
    void fsmUpEntry();
    void fsmUpExit();
    void fsmUpCommandTryingEvent();
    void fsmUpDisconnectEvent();

    virtual void handleEmccmdExecutedMessage(const Container &rx) = 0;
    virtual void handleEmccmdCompletedMessage(const Container &rx) = 0;
    virtual void setConnected() = 0;
    virtual void clearConnected() = 0;

signals:
    void commandUriChanged(const QString &uri);
    void commandMessageReceived(const Container &rx);
    void debugNameChanged(const QString &debugName);
    void stateChanged(CommandBase::State state);
    void errorStringChanged(const QString &errorString);
    void commandHeartbeatIntervalChanged(int interval);
    void readyChanged(bool ready);
    // fsm
    void fsmDownEntered(QPrivateSignal);
    void fsmDownExited(QPrivateSignal);
    void fsmDownConnect(QPrivateSignal);
    void fsmTryingEntered(QPrivateSignal);
    void fsmTryingExited(QPrivateSignal);
    void fsmTryingCommandUp(QPrivateSignal);
    void fsmTryingDisconnect(QPrivateSignal);
    void fsmUpEntered(QPrivateSignal);
    void fsmUpExited(QPrivateSignal);
    void fsmUpCommandTrying(QPrivateSignal);
    void fsmUpDisconnect(QPrivateSignal);
};

} } // namespace machinetalk::application
#endif // APPLICATION_COMMAND_BASE_H
