/****************************************************************************
**
** This code was generated by a code generator based on imatix/gsl
** Any changes in this code will be lost.
**
****************************************************************************/
#include "launchersubscribe.h"
#include "debughelper.h"

#if defined(Q_OS_IOS)
namespace gpb = google_public::protobuf;
#else
namespace gpb = google::protobuf;
#endif

using namespace nzmqt;

namespace application {

/** Generic Launcher Subscribe implementation */
LauncherSubscribe::LauncherSubscribe(QObject *parent) :
    QObject(parent),
    m_ready(false),
    m_debugName("Launcher Subscribe"),
    m_socketUri(""),
    m_context(nullptr),
    m_socket(nullptr),
    m_state(Down),
    m_previousState(Down),
    m_fsm(nullptr),
    m_errorString("")
    ,m_heartbeatTimer(new QTimer(this)),
    m_heartbeatInterval(0),
    m_heartbeatLiveness(0),
    m_heartbeatResetLiveness(2)
{

    m_heartbeatTimer->setSingleShot(true);
    connect(m_heartbeatTimer, &QTimer::timeout, this, &LauncherSubscribe::heartbeatTimerTick);

    m_fsm = new QStateMachine(this);
    QState *downState = new QState(m_fsm);
    connect(downState, &QState::entered, this, &LauncherSubscribe::fsmDownEntered, Qt::QueuedConnection);
    QState *tryingState = new QState(m_fsm);
    connect(tryingState, &QState::entered, this, &LauncherSubscribe::fsmTryingEntered, Qt::QueuedConnection);
    QState *upState = new QState(m_fsm);
    connect(upState, &QState::entered, this, &LauncherSubscribe::fsmUpEntered, Qt::QueuedConnection);
    m_fsm->setInitialState(downState);
    m_fsm->start();

    connect(this, &LauncherSubscribe::fsmDownConnect,
            this, &LauncherSubscribe::fsmDownConnectQueued, Qt::QueuedConnection);
    downState->addTransition(this, &LauncherSubscribe::fsmDownConnectQueued, tryingState);
    connect(this, &LauncherSubscribe::fsmTryingConnected,
            this, &LauncherSubscribe::fsmTryingConnectedQueued, Qt::QueuedConnection);
    tryingState->addTransition(this, &LauncherSubscribe::fsmTryingConnectedQueued, upState);
    connect(this, &LauncherSubscribe::fsmTryingDisconnect,
            this, &LauncherSubscribe::fsmTryingDisconnectQueued, Qt::QueuedConnection);
    tryingState->addTransition(this, &LauncherSubscribe::fsmTryingDisconnectQueued, downState);
    connect(this, &LauncherSubscribe::fsmUpTimeout,
            this, &LauncherSubscribe::fsmUpTimeoutQueued, Qt::QueuedConnection);
    upState->addTransition(this, &LauncherSubscribe::fsmUpTimeoutQueued, tryingState);
    connect(this, &LauncherSubscribe::fsmUpTick,
            this, &LauncherSubscribe::fsmUpTickQueued, Qt::QueuedConnection);
    upState->addTransition(this, &LauncherSubscribe::fsmUpTickQueued, upState);
    connect(this, &LauncherSubscribe::fsmUpMessageReceived,
            this, &LauncherSubscribe::fsmUpMessageReceivedQueued, Qt::QueuedConnection);
    upState->addTransition(this, &LauncherSubscribe::fsmUpMessageReceivedQueued, upState);
    connect(this, &LauncherSubscribe::fsmUpDisconnect,
            this, &LauncherSubscribe::fsmUpDisconnectQueued, Qt::QueuedConnection);
    upState->addTransition(this, &LauncherSubscribe::fsmUpDisconnectQueued, downState);

    connect(this, &LauncherSubscribe::fsmDownConnect,
            this, &LauncherSubscribe::fsmDownConnectEvent, Qt::QueuedConnection);
    connect(this, &LauncherSubscribe::fsmTryingConnected,
            this, &LauncherSubscribe::fsmTryingConnectedEvent, Qt::QueuedConnection);
    connect(this, &LauncherSubscribe::fsmTryingDisconnect,
            this, &LauncherSubscribe::fsmTryingDisconnectEvent, Qt::QueuedConnection);
    connect(this, &LauncherSubscribe::fsmUpTimeout,
            this, &LauncherSubscribe::fsmUpTimeoutEvent, Qt::QueuedConnection);
    connect(this, &LauncherSubscribe::fsmUpTick,
            this, &LauncherSubscribe::fsmUpTickEvent, Qt::QueuedConnection);
    connect(this, &LauncherSubscribe::fsmUpMessageReceived,
            this, &LauncherSubscribe::fsmUpMessageReceivedEvent, Qt::QueuedConnection);
    connect(this, &LauncherSubscribe::fsmUpDisconnect,
            this, &LauncherSubscribe::fsmUpDisconnectEvent, Qt::QueuedConnection);

    m_context = new PollingZMQContext(this, 1);
    connect(m_context, &PollingZMQContext::pollError,
            this, &LauncherSubscribe::socketError);
    m_context->start();

     connect(this, &LauncherSubscribe::startSignal,
             this, &LauncherSubscribe::startSlot, Qt::QueuedConnection);
     connect(this, &LauncherSubscribe::stopSignal,
             this, &LauncherSubscribe::stopSlot, Qt::QueuedConnection);
}

LauncherSubscribe::~LauncherSubscribe()
{
    stopSocket();

    if (m_context != nullptr)
    {
        m_context->stop();
        m_context->deleteLater();
        m_context = nullptr;
    }
}

/** Add a topic that should be subscribed **/
void LauncherSubscribe::addSocketTopic(const QString &name)
{
    m_socketTopics.insert(name);
}

/** Removes a topic from the list of topics that should be subscribed **/
void LauncherSubscribe::removeSocketTopic(const QString &name)
{
    m_socketTopics.remove(name);
}

/** Clears the the topics that should be subscribed **/
void LauncherSubscribe::clearSocketTopics()
{
    m_socketTopics.clear();
}

/** Connects the 0MQ sockets */
bool LauncherSubscribe::startSocket()
{
    m_socket = m_context->createSocket(ZMQSocket::TYP_SUB, this);
    m_socket->setLinger(0);

    try {
        m_socket->connectTo(m_socketUri);
    }
    catch (const zmq::error_t &e) {
        QString errorString;
        errorString = QString("Error %1: ").arg(e.num()) + QString(e.what());
        //updateState(SocketError, errorString); TODO
        return false;
    }

    connect(m_socket, &ZMQSocket::messageReceived,
            this, &LauncherSubscribe::processSocketMessage);


    foreach(QString topic, m_socketTopics)
    {
        m_socket->subscribeTo(topic.toLocal8Bit());
    }

#ifdef QT_DEBUG
    DEBUG_TAG(1, m_debugName, "sockets connected" << m_socketUri);
#endif

    return true;
}

/** Disconnects the 0MQ sockets */
void LauncherSubscribe::stopSocket()
{
    if (m_socket != nullptr)
    {
        m_socket->close();
        m_socket->deleteLater();
        m_socket = nullptr;
    }
}

void LauncherSubscribe::resetHeartbeatLiveness()
{
    m_heartbeatLiveness = m_heartbeatResetLiveness;
}

void LauncherSubscribe::resetHeartbeatTimer()
{
    if (m_heartbeatTimer->isActive())
    {
        m_heartbeatTimer->stop();
    }

    if (m_heartbeatInterval > 0)
    {
        m_heartbeatTimer->setInterval(m_heartbeatInterval);
        m_heartbeatTimer->start();
    }
}

void LauncherSubscribe::startHeartbeatTimer()
{
    resetHeartbeatTimer();
}

void LauncherSubscribe::stopHeartbeatTimer()
{
    m_heartbeatTimer->stop();
}

void LauncherSubscribe::heartbeatTimerTick()
{
    m_heartbeatLiveness -= 1;
    if (m_heartbeatLiveness == 0)
    {
         if (m_state == Up)
         {
             emit fsmUpTimeout();
         }
         return;
    }
    if (m_state == Up)
    {
         emit fsmUpTick();
    }
}

/** Processes all message received on socket */
void LauncherSubscribe::processSocketMessage(const QList<QByteArray> &messageList)
{
    pb::Container &rx = m_socketRx;
    QByteArray topic;

    if (messageList.length() < 2)  // in case we received insufficient data
    {
        return;
    }

    // we only handle the first two messges
    topic = messageList.at(0);
    rx.ParseFromArray(messageList.at(1).data(), messageList.at(1).size());

#ifdef QT_DEBUG
    std::string s;
    gpb::TextFormat::PrintToString(rx, &s);
    DEBUG_TAG(3, m_debugName, "server message" << QString::fromStdString(s));
#endif

    // react to any incoming message

    if (m_state == Up)
    {
        emit fsmUpMessageReceived();
    }

    // react to ping message
    if (rx.type() == pb::MT_PING)
    {
        return; // ping is uninteresting
    }

    // react to launcher full update message
    if (rx.type() == pb::MT_LAUNCHER_FULL_UPDATE)
    {
        if (rx.has_pparams())
        {
            pb::ProtocolParameters pparams = rx.pparams();
            m_heartbeatInterval = pparams.keepalive_timer();
        }

        if (m_state == Trying)
        {
            emit fsmTryingConnected();
        }
    }

    emit socketMessageReceived(topic, rx);
}

void LauncherSubscribe::socketError(int errorNum, const QString &errorMsg)
{
    QString errorString;
    errorString = QString("Error %1: ").arg(errorNum) + errorMsg;
    //updateState(SocketError, errorString);  TODO
}

void LauncherSubscribe::fsmDownEntered()
{
    if (m_previousState != Down)
    {
#ifdef QT_DEBUG
    DEBUG_TAG(1, m_debugName, "State DOWN");
#endif
        m_previousState = Down;
        emit stateChanged(m_state);
    }
}

void LauncherSubscribe::fsmDownConnectEvent()
{
#ifdef QT_DEBUG
    DEBUG_TAG(1, m_debugName, "Event CONNECT");
#endif

    m_state = Trying;
    startSocket();
}

void LauncherSubscribe::fsmTryingEntered()
{
    if (m_previousState != Trying)
    {
#ifdef QT_DEBUG
    DEBUG_TAG(1, m_debugName, "State TRYING");
#endif
        m_previousState = Trying;
        emit stateChanged(m_state);
    }
}

void LauncherSubscribe::fsmTryingConnectedEvent()
{
#ifdef QT_DEBUG
    DEBUG_TAG(1, m_debugName, "Event CONNECTED");
#endif

    m_state = Up;
    resetHeartbeatLiveness();
    startHeartbeatTimer();
}

void LauncherSubscribe::fsmTryingDisconnectEvent()
{
#ifdef QT_DEBUG
    DEBUG_TAG(1, m_debugName, "Event DISCONNECT");
#endif

    m_state = Down;
    stopHeartbeatTimer();
    stopSocket();
}

void LauncherSubscribe::fsmUpEntered()
{
    if (m_previousState != Up)
    {
#ifdef QT_DEBUG
    DEBUG_TAG(1, m_debugName, "State UP");
#endif
        m_previousState = Up;
        emit stateChanged(m_state);
    }
}

void LauncherSubscribe::fsmUpTimeoutEvent()
{
#ifdef QT_DEBUG
    DEBUG_TAG(1, m_debugName, "Event TIMEOUT");
#endif

    m_state = Trying;
    stopHeartbeatTimer();
    stopSocket();
    startSocket();
}

void LauncherSubscribe::fsmUpTickEvent()
{
#ifdef QT_DEBUG
    DEBUG_TAG(1, m_debugName, "Event TICK");
#endif

    m_state = Up;
    resetHeartbeatTimer();
}

void LauncherSubscribe::fsmUpMessageReceivedEvent()
{
#ifdef QT_DEBUG
    DEBUG_TAG(1, m_debugName, "Event MESSAGE RECEIVED");
#endif

    m_state = Up;
    resetHeartbeatLiveness();
    resetHeartbeatTimer();
}

void LauncherSubscribe::fsmUpDisconnectEvent()
{
#ifdef QT_DEBUG
    DEBUG_TAG(1, m_debugName, "Event DISCONNECT");
#endif

    m_state = Down;
    stopHeartbeatTimer();
    stopSocket();
}

/** start trigger */
void LauncherSubscribe::start()
{
    emit startSignal(QPrivateSignal());
}

/** start queued trigger function */
void LauncherSubscribe::startSlot()
{
    if (m_state == Down) {
        emit fsmDownConnect();
    }
}

/** stop trigger */
void LauncherSubscribe::stop()
{
    emit stopSignal(QPrivateSignal());
}

/** stop queued trigger function */
void LauncherSubscribe::stopSlot()
{
    if (m_state == Trying) {
        emit fsmTryingDisconnect();
    }
    if (m_state == Up) {
        emit fsmUpDisconnect();
    }
}
}; // namespace application
