/****************************************************************************
**
** This file was generated by a code generator based on imatix/gsl
** Any changes in this file will be lost.
**
****************************************************************************/
#include "simplesubscribe.h"
#include <google/protobuf/text_format.h>
#include "debughelper.h"

#if defined(Q_OS_IOS)
namespace gpb = google_public::protobuf;
#else
namespace gpb = google::protobuf;
#endif

using namespace nzmqt;

namespace machinetalk { namespace application {

/** Generic Simple Subscribe implementation */
SimpleSubscribe::SimpleSubscribe(QObject *parent)
    : QObject(parent)
    , m_ready(false)
    , m_debugName("Simple Subscribe")
    , m_socketUri("")
    , m_context(nullptr)
    , m_socket(nullptr)
